#include "ggml-turbo-quant.h"

#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <threads.h>  /* C11: once_flag, call_once */

/* ------------------------------------------------------------------ */
/*  Precomputed Lloyd-Max codebooks                                    */
/*  Generated by autoresearch/gen_codebooks.py                        */
/* ------------------------------------------------------------------ */

// 1-bit Lloyd-Max codebooks (2 centroids)
const float tq_codebook_1bit[TURBO_QUANT_NUM_DIMS][2] = {
    /* d=64  */ { -0.10012591f, 0.10012591f },
    /* d=128 */ { -0.07066157f, 0.07066157f },
    /* d=256 */ { -0.04991651f, 0.04991651f },
};

// 2-bit Lloyd-Max codebooks (4 centroids)
const float tq_codebook_2bit[TURBO_QUANT_NUM_DIMS][4] = {
    /* d=64  */ { -0.18749685f, -0.05651487f, 0.05651487f, 0.18749685f },
    /* d=128 */ { -0.13304152f, -0.03999160f, 0.03999159f, 0.13304152f },
    /* d=256 */ { -0.09423778f, -0.02828860f, 0.02828860f, 0.09423778f },
};

/* ------------------------------------------------------------------ */
/*  Dimension index helper  (64->0, 128->1, 256->2)                   */
/* ------------------------------------------------------------------ */
static int _tq_dim_index(int dim) {
    switch (dim) {
        case  64: return 0;
        case 128: return 1;
        case 256: return 2;
        default:  return -1;   /* unsupported */
    }
}

/* ------------------------------------------------------------------ */
/*  Block size helpers                                                  */
/* ------------------------------------------------------------------ */

size_t tq_mse_block_size(int dim) {
    /* 4 bytes (norm) + ceil(2*dim/8) bytes (2-bit packed indices) */
    return 4 + (size_t)((2 * dim + 7) / 8);
}

size_t tq_prod_block_size(int dim) {
    /* 4 (norm) + 4 (gamma) + ceil(1*dim/8) (MSE indices at 1 bit)
     * + ceil(1*dim/8) (QJL sign bits)                              */
    return 4 + 4 + (size_t)((dim + 7) / 8) + (size_t)((dim + 7) / 8);
}

/* ------------------------------------------------------------------ */
/*  Rotation matrix seed                                                */
/* ------------------------------------------------------------------ */

uint64_t tq_rotation_seed(int dim, int quant_type_id) {
    return (uint64_t)dim * 65537ULL + (uint64_t)quant_type_id;
}

/* ------------------------------------------------------------------ */
/*  Simple Marsaglia Polar PRNG (produces N(0,1) samples)             */
/* ------------------------------------------------------------------ */

typedef struct {
    uint64_t state;
} tq_prng_t;

static void tq_prng_seed(tq_prng_t *rng, uint64_t seed) {
    rng->state = seed ^ 0x6c62272e07bb0142ULL;
    if (rng->state == 0) rng->state = 1;
}

/* xorshift64 */
static uint64_t tq_prng_u64(tq_prng_t *rng) {
    uint64_t x = rng->state;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    rng->state = x;
    return x;
}

/* Uniform in (0, 1) */
static double tq_prng_uniform(tq_prng_t *rng) {
    return (double)(tq_prng_u64(rng) >> 11) * (1.0 / (double)(1ULL << 53));
}

/* Box-Muller: one N(0,1) sample (produces pairs; we discard the second) */
static double tq_prng_normal(tq_prng_t *rng) {
    double u, v, s;
    do {
        u = 2.0 * tq_prng_uniform(rng) - 1.0;
        v = 2.0 * tq_prng_uniform(rng) - 1.0;
        s = u * u + v * v;
    } while (s >= 1.0 || s == 0.0);
    return u * sqrt(-2.0 * log(s) / s);
}

/* ------------------------------------------------------------------ */
/*  Gram-Schmidt QR orthonormalisation (in-place, row-major)          */
/*  A is n×n.  After return the rows of A are orthonormal.            */
/* ------------------------------------------------------------------ */
static void _tq_qr_inplace(float *A, int n) {
    for (int i = 0; i < n; i++) {
        float *vi = A + (size_t)i * n;

        /* Subtract projections onto previous rows */
        for (int j = 0; j < i; j++) {
            const float *vj = A + (size_t)j * n;
            double dot = 0.0;
            for (int k = 0; k < n; k++) {
                dot += (double)vi[k] * (double)vj[k];
            }
            for (int k = 0; k < n; k++) {
                vi[k] -= (float)(dot * (double)vj[k]);
            }
        }

        /* Normalise */
        double norm2 = 0.0;
        for (int k = 0; k < n; k++) {
            norm2 += (double)vi[k] * (double)vi[k];
        }
        double inv_norm = (norm2 > 1e-30) ? 1.0 / sqrt(norm2) : 0.0;
        for (int k = 0; k < n; k++) {
            vi[k] = (float)((double)vi[k] * inv_norm);
        }
    }
}

/* ------------------------------------------------------------------ */
/*  Rotation matrix storage                                             */
/*  We support 3 dims: 64, 128, 256.                                  */
/* ------------------------------------------------------------------ */
#define TQ_NUM_DIMS 3
static const int tq_dims[TQ_NUM_DIMS] = {64, 128, 256};

/* Pi (rotation) and S (Gaussian) matrices, one per supported dim.    */
static float *tq_Pi[TQ_NUM_DIMS] = {NULL, NULL, NULL};
static float *tq_S[TQ_NUM_DIMS]  = {NULL, NULL, NULL};

static once_flag tq_init_flag = ONCE_FLAG_INIT;
static bool      tq_ready     = false;

static void _tq_do_init(void) {
    for (int di = 0; di < TQ_NUM_DIMS; di++) {
        int d = tq_dims[di];
        size_t n_elems = (size_t)d * d;

        /* ---- Allocate Pi ---- */
        tq_Pi[di] = (float *)malloc(n_elems * sizeof(float));
        if (!tq_Pi[di]) { return; }

        /* Fill with N(0,1) using seed for Pi */
        tq_prng_t rng;
        tq_prng_seed(&rng, tq_rotation_seed(d, (int)GGML_TYPE_TQ_MSE));
        for (size_t i = 0; i < n_elems; i++) {
            tq_Pi[di][i] = (float)tq_prng_normal(&rng);
        }

        /* Gram-Schmidt to make rows orthonormal */
        _tq_qr_inplace(tq_Pi[di], d);

        /* ---- Allocate S ---- */
        tq_S[di] = (float *)malloc(n_elems * sizeof(float));
        if (!tq_S[di]) { return; }

        /* Fill S with N(0,1) — different seed */
        tq_prng_seed(&rng, tq_rotation_seed(d, (int)GGML_TYPE_TQ_PROD));
        for (size_t i = 0; i < n_elems; i++) {
            tq_S[di][i] = (float)tq_prng_normal(&rng);
        }
        /* S is NOT orthonormalised; it stays as Gaussian per the algorithm */
    }
    tq_ready = true;
}

void tq_init_rotations(void) {
    call_once(&tq_init_flag, _tq_do_init);
}

bool tq_rotations_ready(void) {
    return tq_ready;
}

/* ------------------------------------------------------------------ */
/*  Matrix row accessors                                                */
/* ------------------------------------------------------------------ */

const float * tq_get_Pi_row(int dim, int row) {
    int di = _tq_dim_index(dim);
    if (di < 0 || !tq_Pi[di]) { return NULL; }
    return tq_Pi[di] + (size_t)row * dim;
}

const float * tq_get_S_row(int dim, int row) {
    int di = _tq_dim_index(dim);
    if (di < 0 || !tq_S[di]) { return NULL; }
    return tq_S[di] + (size_t)row * dim;
}
